routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//{
//    Route::post('/bulk/feature', function(\Illuminate\Http\Request $request){
//        foreach ($request->all() as $req){
//            $req = (object) $req;
//            $listing = \App\Listing::where('title', $req->title)->first();
//            if(!is_null($listing)) {
//                $feature = \App\HouseFeature::where('name', $req->detail)->first();
//                if (is_null($feature)) {
//                    $feature = \App\HouseFeature::create([
//                        'id' => uid('SRN'),
//                        'name' => $req->detail,
//                        'type' => 1,
//                    ]);
//                }
//
//                \App\HouseFeatureDetail::create([
//                    'id' => uid('FD'),
//                    'house_feature_id' => $feature->id,
//                    'listing_id' => $listing->id,
//                    'value' => $req->value
//                ]);
//            }
//        }
//    });
//
//    Route::post('/bulk/details', function(\Illuminate\Http\Request $request){
////    return $request;
//        foreach ($request->all() as $req){
//            try{
////            \Illuminate\Support\Facades\DB::beginTransaction();
//                $req = (object) $req;
//                $listing = \App\Listing::where('title', $req->title)->first();
//                if(!is_null($listing)){
//                    if($req->detail == "Kamar tidur"){
//                        $listing->update([
//                            'kamar_tidur' => $req->value
//                        ]);
//                    } else if($req->detail == "Kamar mandi"){
//                        $listing->update([
//                            'kamar_mandi' => $req->value
//                        ]);
//                    } else if($req->detail == "Bangunan (m²)"){
//                        $listing->update([
//                            'luas_bangunan' => $req->value
//                        ]);
//                    } else if($req->detail == "Lahan (m²)"){
//                        $listing->update([
//                            'luas_tanah' => $req->value
//                        ]);
//                    } else {
//                        // TODO : Create or Fail House Feature
//                        $feature = \App\HouseFeature::where('name', $req->detail)->first();
//                        if(is_null($feature)){
//                            $feature = \App\HouseFeature::create([
//                                'id' => uid('SRN'),
//                                'name' => $req->detail,
//                                'type' => 3,
//                            ]);
//                        }
//
//                        \App\HouseFeatureDetail::create([
//                            'id' => uid('FD'),
//                            'house_feature_id' => $feature->id,
//                            'listing_id' => $listing->id,
//                            'value' => $req->value
//                        ]);
//                    }
////                \Illuminate\Support\Facades\DB::commit();
//                }
//            } catch (Exception $e){
//                echo $e;
////            \Illuminate\Support\Facades\DB::rollBack();
//            }
//        }
//    });
//
//}

Auth::routes();
Route::redirect('/home', '/');
Route::get('/verification/{token}', 'HomeController@verification')->name('verificaiton');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/sell', 'HomeController@sell')->name('sell');
Route::get('/listing/{listing}', 'HomeController@detailListing')->name('detail-listing');
Route::get('/profile/{id}', 'HomeController@getProfile')->name('detail-profile');
Route::post('/listing/order', 'HomeController@orderListingTemp')->name('order-listing');
Route::view('/test', 'emails.test');

Route::get('cekrumah', 'HomeController@underConstruction')->name('cekrumah');

Route::get('/dashboard', function () {
    $role = \Illuminate\Support\Facades\Auth::user()->role->role;
    if ($role == "admin") {
        return redirect()->route('admin.dashboard');
    } else if ($role == "surveyor") {
        return redirect()->route('surveyor.dashboard');
    } else if ($role == "member") {
        return redirect()->route('member.dashboard');
    } else if ($role == "mitra") {
        return redirect()->route('mitra.dashboard');
    }
})->middleware('auth')->name('dashboard');

Route::group(['prefix' => 'ajax', 'as' => 'ajax.', 'namespace' => 'Ajax'], function () {
    Route::get('/kabupaten/{id}', 'HomeController@getKabupaten')->name('kabupaten');
    Route::get('/kecamatan/{id}', 'HomeController@getKota')->name('kecamatan');

    Route::get('/admin/listing', 'AdminController@getListing')->name('admin.listing');
    Route::get('/admin/order', 'AdminController@getOrder')->name('admin.order');
    Route::get('/admin/house-feature', 'AdminController@getSarana')->name('admin.house-feature');
    Route::get('/listing/remain-house-feature/{id}', 'AdminController@getRemainHouseFeatureListing')->name('admin.listing-remain-house-feature');
    Route::get('/listing/house-feature/{id}', 'AdminController@getHouseFeatureListing')->name('admin.listing-house-feature');

    Route::group(['prefix' => 'member', 'as' => 'member.'], function(){
        Route::get('/wishlist', 'MemberController@getWishlist')->name('get-wishlist');
    });

    Route::group(['prefix' => 'mitra', 'as' => 'mitra.'], function(){
        Route::get('/listing', 'MitraController@getListing')->name('listing');
    });
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['role:admin']], function () {

    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/listing', 'ListingController@index')->name('listing');
    Route::get('/listing/create', 'ListingController@create')->name('listing.create');
    Route::post('/listing/store', 'ListingController@store')->name('listing.store');
    Route::get('/listing/detail/{id}', 'ListingController@detail')->name('listing.detail');
    Route::get('/listing/edit/{id}', 'ListingController@edit')->name('listing.edit');
    Route::post('/listing/update/status', 'ListingController@updateStatus')->name('listing.update.status');
    Route::post('/listing/update/{id}', 'ListingController@update')->name('listing.update');
    Route::get('/listing/feature/add/{id}/{feature}/{value}', 'ListingController@addFeature');
    Route::post('/listing/image/upload/{id}', 'ListingController@uploadImage');
    Route::post('/listing/image/remove/{id}', 'ListingController@removeImage');

    Route::get('/house-order', 'OrderHouseController@index')->name('house-order');
    Route::get('/house-order/detail/{id}', 'OrderHouseController@detail')->name('house-order.detail');

    Route::get('/house-feature', 'HouseFeatureController@index')->name('house-feature');
    Route::get('/house-feature/create', 'HouseFeatureController@create')->name('house-feature.create');
    Route::post('/house-feature', 'HouseFeatureController@store')->name('house-feature.store');
    Route::get('/house-feature/detail/{id}', 'HouseFeatureController@detail')->name('house-feature.detail');
    Route::delete('/house-feature', 'HouseFeatureController@destroy')->name('house-feature.destroy');
});

Route::group(['prefix' => 'member', 'as' => 'member.', 'namespace' => 'Member', 'middleware' => ['role:member']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/wishlist', 'HouseOrderController');
});

Route::group(['prefix' => 'surveyor', 'as' => 'surveyor.', 'namespace' => 'Surveyor', 'middleware' => ['role:surveyor']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
});

Route::group(['prefix' => 'mitra', 'as' => 'mitra.', 'namespace' => 'Mitra', 'middleware' => ['role:mitra']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('listing', 'ListingController');
    Route::get('/listing/feature/add/{id}/{feature}/{value}', 'ListingController@addFeature');
    Route::post('/listing/image/upload/{id}', 'ListingController@uploadImage');
    Route::post('/listing/image/remove/{id}', 'ListingController@removeImage');
    Route::get('/profile', 'ProfileController@index')->name('profile.index');
    Route::post('/profile', 'ProfileController@store')->name('profile.store');
});


Route::get('test', function(){
    return new \App\Mail\RegisterMail(\App\User::first());
});

Route::get('ttt', function(){
    $user = \App\User::find('U0343157');
    return view('profile-detail', compact('user'));
});

app/Http/Controllers/Admin/ListingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\HouseFeatureDetail;
use App\Listing;
use App\Province;
use App\Upload;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ListingController extends Controller
{
    public function index(){
        return view('dashboard.admin.listing');
    }

    public function create(){
        $provinces = Province::all();
        return view('dashboard.admin.listing-add', compact('provinces'));
    }

    public function detail($id){
        $listing = Listing::findOrFail($id);
        return view('dashboard.admin.listing-detail', compact('listing'));
    }

    public function edit($id){
        $listing = Listing::findOrFail($id);
        $provinces = Province::all();
        return view('dashboard.admin.listing-edit', compact('listing', 'provinces'));
    }

    public function store(Request $request){
        Listing::create([
            'id' => uid('L', 8),
            'user_id' => Auth::id(),
            'district_id' => $request->district_id,
            'title' => $request->title,
            'luas_tanah' => $request->luas_tanah,
            'luas_bangunan' => $request->luas_bangunan,
            'kamar_tidur' => $request->kamar_tidur,
            'kamar_mandi' => $request->kamar_mandi,
            'harga' => $request->harga,
            'listrik' => $request->listrik,
            'alamat' => $request->alamat,
            'lokasi' => json_encode([
                'longitude' => $request->longitude,
                'latitude' => $request->latitude
            ]),
            'deskripsi' => $request->deskripsi,
        ]);
        toastr()->success("Listing berhasil dibuat");
        return redirect()->rotue('admin.listing');
    }

    public function update($id, Request $request){
        $listing = Listing::findOrFail($id);
        $listing->update([
            'title' => $request->title,
            'luas_tanah' => $request->luas_tanah,
            'luas_bangunan' => $request->luas_bangunan,
            'harga' => $request->harga,
            'listrik' => $request->listrik,
            'alamat' => $request->alamat,
            'deskripsi' => $request->deskripsi,
            'district_id' => $request->district_id,
            'kamar_mandi' => $request->kamar_mandi,
            'kamar_tidur' => $request->kamar_tidur,
            'lokasi' => json_encode([
                'longitude' => $request->longitude,
                'latitude' => $request->latitude
            ])
        ]);
        toastr()->success('Data berhasil diubah');
        return redirect()->route('admin.listing');
    }

    public function addFeature($id, $feature_id, $val){
        HouseFeatureDetail::create([
            'id' => uid('FTD'),
            'house_feature_id' => $feature_id,
            'listing_id' => $id,
            'value' => $val
        ]);
        return $id . "--" . $feature_id . "--" . $val;
    }

    public function uploadImage($id, Request $request){
        $listing = Listing::findOrFail($id);
        if ($request->hasFile('file')) {
            $file = $request->file('file');
            $path = Storage::disk('public')->put('listings/' . $listing->id . '', $file);
            $thumbnail = Image::make($file)->fit(120, 120)->encode($file->getClientOriginalExtension(), 100);
            Storage::disk('public')->put('listing-thumbnail/' . $path, $thumbnail);
            $upload = Upload::create([
                'id' => uid('G'),
                'listing_id' => $listing->id,
                'thumbnail' => 'listing-thumbnail/' . $path,
                'size' => $file->getSize(),
                'path' => $path
            ]);
            return $upload;
        } else {
            return "failed";
            // echo "<span class='text-danger'>No such a file</span>";
        }
    }

    public function removeImage($id, Request $request){
        $filename = $request->filename;
        $listing = Listing::findOrFail($id);
        $uploads = Upload::where('path', $filename)->firstOrFail()->delete();
        Storage::disk('public')->delete($filename);
        return "success delete";
    }

    public function updateStatus(Request $request){
        $listing = Listing::findOrFail($request->listing);
        if(!in_array($request->status, [2,3,4,5])){
            toastr()->error("Something error");
            return redirect()->back();
        }
        $listing->update([
            'status' => $request->status
        ]);
        toastr()->success("Perubahan berhasil");
        return redirect()->back();
    }
}

app/Http/Controllers/Ajax/MitraController.php
<?php

namespace App\Http\Controllers\Ajax;

use App\Listing;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class MitraController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:mitra');
    }

    public function getListing()
    {
        $listings = Auth::user()->listings;
        foreach ($listings as $index => $listing) {
            $listing->no = $index + 1;
        }

        return DataTables::of($listings)
            ->addColumn('judul', function ($q) {
                return substr($q->title, 0, 50);
            })
            ->addColumn('provinsi', function ($q) {
                return $q->district->regency->province->name;
            })
            ->addColumn('l_tanah', function ($q) {
                return $q->luas_tanah . ' m';
            })
            ->addColumn('l_bangunan', function ($q) {
                return $q->luas_bangunan . ' m';
            })
            ->addColumn('harga_format', function ($q) {
                return price_format($q->harga);
            })
            ->addColumn('action', function($q){
                if($q->status == 1){
                    return "Belum Disetujui";
                } else if($q->status == 2){
                    return "<button class=\"btn btn-danger\" onclick=\"action('deactivate', ". $q->id .")\">Nonaktifkan</button>";
                } else if($q->status == 3){
                    return "<button class=\"btn btn-primary\" onclick=\"action('activate', ". $q->id .")\">Aktifkan</button>";
                } else {
                    return "Diblockir Admin";
                }
            })
            ->make(true);
    }
}

app/Http/Controllers/Mitra/DashboardController.php
<?php

namespace App\Http\Controllers\Mitra;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index(){
        return view('dashboard.mitra.index');
    }
}

app/Http/Controllers/Mitra/ProfileController.php
<?php

namespace App\Http\Controllers\Mitra;

use App\Listing;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ProfileController extends Controller
{
    public function index(){
        $user = Auth::user();
        return view('dashboard.mitra.profile.index', compact('user'));
    }

    public function store(Request $request){
        $this->validate($request, [
            'name' => 'required',
            'no_hp' => 'required',
            'alamat' => 'required'
        ]);

        if(!is_null($request->avatar)){
            if(!is_null(Auth::user()->info->avatar)){
                unlink(storage_path('app/public/' . Auth::user()->info->avatar));
            }
            $path = Storage::disk('public')->put('assets/avatar', $request->avatar);
        } else {
            $path = null;
        }


        Auth::user()->update([
            'name' => $request->name
        ]);

        Auth::user()->info->update([
            'no_hp' => $request->no_hp,
            'alamat' => $request->alamat,
            'description' => $request->description,
            'avatar' => $path
        ]);

        toastr()->success("Profil Berhasil diubah");
        return redirect()->back();
    }
}

resources/views/dashboard/mitra/listing/index.blade.php
@extends('dashboard.layouts.app')

@section('title', 'Listing')

@section('css')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('dashboard-assets/modules/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard-assets/modules/css/select.bootstrap4.min.css') }}">
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Daftar Properti</h1>
            <div class="section-header-button">
                <a href="{{ route('mitra.listing.create') }}" class="btn btn-primary">Tambah</a>
            </div>
            <div class="section-header-breadcrumb">
            </div>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Data Listing</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped" id="listing-table">
                                    <thead>
                                    <tr>
                                        <th class="text-center">
                                            #
                                        </th>
                                        <th>Judul</th>
                                        <th>Luas Tanah</th>
                                        <th>Luas Bangunan</th>
                                        <th>Provinsi</th>
                                        <th>Harga</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection


@section('js')
    <!-- JS Libraies -->
    <script src="{{ asset('dashboard-assets/modules/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('dashboard-assets/modules/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('dashboard-assets/modules/js/select.bootstrap4.min.js') }}"></script>

    <script>
        $('#listing-table').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{ route('ajax.mitra.listing') }}",
            createdRow: function(row, data, index){
                $(row).addClass('clickable-row');
                $(row).attr('data-href', '/mitra/listing/' + data['id']);
            },
            columns: [
                {data: 'no', name: 'no'},
                {data: 'judul', name: 'judul'},
                {data: 'l_tanah', name: 'l_tanah'},
                {data: 'l_bangunan', name: 'l_bangunan'},
                {data: 'provinsi', name: 'provinsi'},
                {data: 'harga_format', name: 'harga_format'},
                {data: 'action', name: 'action'},
            ],
            drawCallback: function(){
                $('.clickable-row').on('click', function(){
                    window.location = $(this).data('href') + "/edit";
                });
            }
        });
    </script>
@endsection

resources/views/dashboard/mitra/listing/show.blade.php
@extends('dashboard.layouts.app')

@section('title', 'Home')

@section('css')

@endsection

@section('content')
    <div class="main-content-inner">
        <div class="row">
            <div class="col-12 mt-5">
                <div class="card">
                    <div class="card-body">
                        @if(Auth::user()->can('update', $listing))
                            <button class="btn btn-primary float-right" id="edit-button">
                                Edit
                            </button>
                        @endif
                        <h4 class="header-title">{{ $listing->title }}</h4>
                        <small>{{ date('F, d Y | H:i:s', strtotime($listing->created_at)) }}</small>
                        <br>
                        <br>
                        <!--Carousel Wrapper-->
                        <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
                            <!--Indicators-->
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-1z" data-slide-to="1"></li>
                                <li data-target="#carousel-example-1z" data-slide-to="2"></li>
                            </ol>
                            <!--/.Indicators-->
                            <!--Slides-->
                            <div class="carousel-inner" role="listbox">
                                @foreach($listing->uploads as $index => $upload)
                                    <div class="carousel-item {{ $index == 0 ? 'active' : '' }}">
                                        <img class="d-block w-100" height="500px"
                                             src="{{ asset('storage/' . $upload->path) }}"
                                             alt="">
                                    </div>
                                @endforeach
                                <!--First slide-->
                                <!--/First slide-->
                                {{--<!--Second slide-->--}}
                                {{--<div class="carousel-item">--}}
                                    {{--<img class="d-block w-100"--}}
                                         {{--src="https://mdbootstrap.com/img/Photos/Slides/img%20(129).jpg"--}}
                                         {{--alt="Second slide">--}}
                                {{--</div>--}}
                                {{--<!--/Second slide-->--}}
                                {{--<!--Third slide-->--}}
                                {{--<div class="carousel-item">--}}
                                    {{--<img class="d-block w-100"--}}
                                         {{--src="https://mdbootstrap.com/img/Photos/Slides/img%20(70).jpg"--}}
                                         {{--alt="Third slide">--}}
                                {{--</div>--}}
                                {{--<!--/Third slide-->--}}
                            </div>
                            <!--/.Slides-->
                            <!--Controls-->
                            <a class="carousel-control-prev" href="#carousel-example-1z" role="button"
                               data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel-example-1z" role="button"
                               data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                            <!--/.Controls-->
                        </div>
                        <br>
                        <hr>
                        <!--/.Carousel Wrapper-->
                        <h4>Detail</h4>
                        <br>
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <td>Luas Tanah</td>
                                <td>{{ $listing->luas_tanah }} m</td>
                            </tr>
                            <tr>
                                <td>Luas Bangunan</td>
                                <td>{{ $listing->luas_bangunan }} m</td>
                            </tr>
                            <tr>
                                <td>Harga</td>
                                <td>{{ price_format($listing->harga) }}</td>
                            </tr>
                            <tr>
                                <td>Daya Listrik</td>
                                <td>{{ $listing->listrik }} W</td>
                            </tr>
                            <tr>
                                <td>Alamat</td>
                                <td>{{ $listing->alamat }} </td>
                            </tr>
                            <tr>
                                <td>Lokasi</td>
                                <td>
                                    Longtitude : {{ json_decode($listing->lokasi, true)["longitude"] }} <br>
                                    Langtitude : {{ json_decode($listing->lokasi, true)["latitude"] }}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <h4>Deskripsi</h4>
                        <p>{{ $listing->deskripsi }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('js')
    <script>
        $('#edit-button').on('click', function () {
            window.location = '/mitra/listing/{{ $listing->id }}/edit';
        });
    </script>
@endsection