routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//{
//    Route::post('/bulk/feature', function(\Illuminate\Http\Request $request){
//        foreach ($request->all() as $req){
//            $req = (object) $req;
//            $listing = \App\Listing::where('title', $req->title)->first();
//            if(!is_null($listing)) {
//                $feature = \App\HouseFeature::where('name', $req->detail)->first();
//                if (is_null($feature)) {
//                    $feature = \App\HouseFeature::create([
//                        'id' => uid('SRN'),
//                        'name' => $req->detail,
//                        'type' => 1,
//                    ]);
//                }
//
//                \App\HouseFeatureDetail::create([
//                    'id' => uid('FD'),
//                    'house_feature_id' => $feature->id,
//                    'listing_id' => $listing->id,
//                    'value' => $req->value
//                ]);
//            }
//        }
//    });
//
//    Route::post('/bulk/details', function(\Illuminate\Http\Request $request){
////    return $request;
//        foreach ($request->all() as $req){
//            try{
////            \Illuminate\Support\Facades\DB::beginTransaction();
//                $req = (object) $req;
//                $listing = \App\Listing::where('title', $req->title)->first();
//                if(!is_null($listing)){
//                    if($req->detail == "Kamar tidur"){
//                        $listing->update([
//                            'kamar_tidur' => $req->value
//                        ]);
//                    } else if($req->detail == "Kamar mandi"){
//                        $listing->update([
//                            'kamar_mandi' => $req->value
//                        ]);
//                    } else if($req->detail == "Bangunan (m²)"){
//                        $listing->update([
//                            'luas_bangunan' => $req->value
//                        ]);
//                    } else if($req->detail == "Lahan (m²)"){
//                        $listing->update([
//                            'luas_tanah' => $req->value
//                        ]);
//                    } else {
//                        // TODO : Create or Fail House Feature
//                        $feature = \App\HouseFeature::where('name', $req->detail)->first();
//                        if(is_null($feature)){
//                            $feature = \App\HouseFeature::create([
//                                'id' => uid('SRN'),
//                                'name' => $req->detail,
//                                'type' => 3,
//                            ]);
//                        }
//
//                        \App\HouseFeatureDetail::create([
//                            'id' => uid('FD'),
//                            'house_feature_id' => $feature->id,
//                            'listing_id' => $listing->id,
//                            'value' => $req->value
//                        ]);
//                    }
////                \Illuminate\Support\Facades\DB::commit();
//                }
//            } catch (Exception $e){
//                echo $e;
////            \Illuminate\Support\Facades\DB::rollBack();
//            }
//        }
//    });
//
//}

Auth::routes();
Route::redirect('/home', '/');
Route::get('/verification/{token}', 'HomeController@verification')->name('verificaiton');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/sell', 'HomeController@sell')->name('sell');
Route::get('/listing/{listing}', 'HomeController@detailListing')->name('detail-listing');
Route::get('/profile/{id}', 'HomeController@getProfile')->name('detail-profile');
Route::post('/listing/order', 'HomeController@orderListingTemp')->name('order-listing');
Route::view('/test', 'emails.test');

Route::get('cekrumah', 'HomeController@underConstruction')->name('cekrumah');

Route::get('/dashboard', function () {
    $role = \Illuminate\Support\Facades\Auth::user()->role->role;
    if ($role == "admin") {
        return redirect()->route('admin.dashboard');
    } else if ($role == "surveyor") {
        return redirect()->route('surveyor.dashboard');
    } else if ($role == "member") {
        return redirect()->route('member.dashboard');
    } else if ($role == "mitra") {
        return redirect()->route('mitra.dashboard');
    }
})->middleware('auth')->name('dashboard');

Route::group(['prefix' => 'ajax', 'as' => 'ajax.', 'namespace' => 'Ajax'], function () {
    Route::get('/kabupaten/{id}', 'HomeController@getKabupaten')->name('kabupaten');
    Route::get('/kecamatan/{id}', 'HomeController@getKota')->name('kecamatan');

    Route::get('/admin/listing', 'AdminController@getListing')->name('admin.listing');
    Route::get('/admin/order', 'AdminController@getOrder')->name('admin.order');
    Route::get('/admin/house-feature', 'AdminController@getSarana')->name('admin.house-feature');
    Route::get('/listing/remain-house-feature/{id}', 'AdminController@getRemainHouseFeatureListing')->name('admin.listing-remain-house-feature');
    Route::get('/listing/house-feature/{id}', 'AdminController@getHouseFeatureListing')->name('admin.listing-house-feature');

    Route::group(['prefix' => 'member', 'as' => 'member.'], function(){
        Route::get('/wishlist', 'MemberController@getWishlist')->name('get-wishlist');
    });

    Route::group(['prefix' => 'mitra', 'as' => 'mitra.'], function(){
        Route::get('/listing', 'MitraController@getListing')->name('listing');
    });
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['role:admin']], function () {

    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/listing', 'ListingController@index')->name('listing');
    Route::get('/listing/create', 'ListingController@create')->name('listing.create');
    Route::post('/listing/store', 'ListingController@store')->name('listing.store');
    Route::get('/listing/detail/{id}', 'ListingController@detail')->name('listing.detail');
    Route::get('/listing/edit/{id}', 'ListingController@edit')->name('listing.edit');
    Route::post('/listing/update/status', 'ListingController@updateStatus')->name('listing.update.status');
    Route::post('/listing/update/{id}', 'ListingController@update')->name('listing.update');
    Route::get('/listing/feature/add/{id}/{feature}/{value}', 'ListingController@addFeature');
    Route::post('/listing/image/upload/{id}', 'ListingController@uploadImage');
    Route::post('/listing/image/remove/{id}', 'ListingController@removeImage');

    Route::get('/house-order', 'OrderHouseController@index')->name('house-order');
    Route::get('/house-order/detail/{id}', 'OrderHouseController@detail')->name('house-order.detail');

    Route::get('/house-feature', 'HouseFeatureController@index')->name('house-feature');
    Route::get('/house-feature/create', 'HouseFeatureController@create')->name('house-feature.create');
    Route::post('/house-feature', 'HouseFeatureController@store')->name('house-feature.store');
    Route::get('/house-feature/detail/{id}', 'HouseFeatureController@detail')->name('house-feature.detail');
    Route::delete('/house-feature', 'HouseFeatureController@destroy')->name('house-feature.destroy');
});

Route::group(['prefix' => 'member', 'as' => 'member.', 'namespace' => 'Member', 'middleware' => ['role:member']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/wishlist', 'HouseOrderController');
});

Route::group(['prefix' => 'surveyor', 'as' => 'surveyor.', 'namespace' => 'Surveyor', 'middleware' => ['role:surveyor']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
});

Route::group(['prefix' => 'mitra', 'as' => 'mitra.', 'namespace' => 'Mitra', 'middleware' => ['role:mitra']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('listing', 'ListingController');
    Route::get('/listing/feature/add/{id}/{feature}/{value}', 'ListingController@addFeature');
    Route::post('/listing/image/upload/{id}', 'ListingController@uploadImage');
    Route::post('/listing/image/remove/{id}', 'ListingController@removeImage');
    Route::get('/profile', 'ProfileController@index')->name('profile.index');
    Route::post('/profile', 'ProfileController@store')->name('profile.store');
});


Route::get('test', function(){
    return new \App\Mail\RegisterMail(\App\User::first());
});

Route::get('ttt', function(){
    $user = \App\User::find('U0343157');
    return view('profile-detail', compact('user'));
});

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function __construct()
    {

    }

    public function index(){
        return view('dashboard.admin.index');
    }
}

app/Http/Controllers/Member/DashboardController.php
<?php

namespace App\Http\Controllers\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index(){
        return view('dashboard.member.index');
    }
}

app/Http/Controllers/Mitra/DashboardController.php
<?php

namespace App\Http\Controllers\Mitra;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index(){
        return view('dashboard.mitra.index');
    }
}

app/Http/Controllers/Surveyor/DashboardController.php
<?php

namespace App\Http\Controllers\Surveyor;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index(){
        return view('dashboard.surveyor.index');
    }
}

resources/views/dashboard/admin/house-feature-create.blade.php
@extends('dashboard.layouts.app')

@section('title', 'Tambah Sarana')

@section('css')

@endsection

@section('content')
    <div class="main-content-inner">
        <div class="row">
            <div class="col-12 mt-5">
                <div class="card">
                    <div class="card-body">
                        <h4>Tambah Sarana</h4>
                        <br>
                        <form action="{{ route('admin.house-feature.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="title">Nama Sarana</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Tipe Sarana</label>
                                <select name="type" id="type" class="form-control">
                                    @foreach($types as $index => $type)
                                        <option value="{{ $index }}">{{ $type }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <input type="submit" value="Submit" class="btn btn-primary float-right">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('js')
    <script>

    </script>
@endsection

resources/views/dashboard/admin/house-feature.blade.php
@extends('dashboard.layouts.app')

@section('title', 'Listing')

@section('css')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('dashboard-assets/modules/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard-assets/modules/css/select.bootstrap4.min.css') }}">
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Sarana</h1>
            <div class="section-header-button">
                <a href="{{ route('admin.house-feature.create') }}" class="btn btn-primary">Add New</a>
            </div>
            <div class="section-header-breadcrumb">
            </div>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Data Sarana</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped" id="feature-table">
                                    <thead>
                                    <tr>
                                        <th class="text-center">
                                            #
                                        </th>
                                        <th>Sarana</th>
                                        <th>Jenis Data</th>
                                        <th>Jumlah Listing</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection


@section('js')
    <!-- JS Libraies -->
    <script src="{{ asset('dashboard-assets/modules/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('dashboard-assets/modules/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('dashboard-assets/modules/js/select.bootstrap4.min.js') }}"></script>

    <script>
        $('#add-button').on('click', function () {
            window.location = '{{ route('admin.house-feature.create')  }}'
        });

        $('#feature-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('ajax.admin.house-feature') }}",
            columns: [
                {data: 'no', name: 'no'},
                {data: 'name', name: 'name'},
                {data: 'type', name: 'type'},
                {data: 'jumlah', name: 'jumlah'},
                {data: 'delete', name: 'delete'},
            ]
        });

        function deleteData(id) {
            $('#delete-id').val(id);
            $('#delete-form').submit();
        }
    </script>
@endsection

{{--@extends('dashboard.layouts.app')--}}

{{--@section('title', 'Sarana')--}}

{{--@section('css')--}}

{{--@endsection--}}

{{--@section('content')--}}
    {{--<div class="main-content-inner">--}}
        {{--<div class="row">--}}
            {{--<div class="col-12 mt-5">--}}
                {{--<div class="card">--}}
                    {{--<div class="card-body">--}}
                        {{--<button class="btn btn-primary float-right" id="add-button">--}}
                            {{--Tambah--}}
                        {{--</button>--}}
                        {{--<br>--}}
                        {{--<h4 class="header-title">Sarana</h4>--}}
                        {{--<div class="data-tables">--}}
                            {{--<table id="sarana-table" class="text-center">--}}
                                {{--<thead class="bg-light text-capitalize">--}}
                                {{--<tr>--}}
                                    {{--<th>No</th>--}}
                                    {{--<th>Sarana</th>--}}
                                    {{--<th>Jenis Data</th>--}}
                                    {{--<th>Jumlah Listing</th>--}}
                                    {{--<th>Action</th>--}}
                                {{--</tr>--}}
                                {{--</thead>--}}
                                {{--<tbody>--}}

                                {{--</tbody>--}}
                            {{--</table>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}
    {{--<form action="{{ route('admin.house-feature.destroy') }}" id="delete-form" method="post">--}}
        {{--@csrf--}}
        {{--@method('DELETE')--}}
        {{--<input type="hidden" id="delete-id" name="id">--}}
    {{--</form>--}}
{{--@endsection--}}


{{--@section('js')--}}
    {{--<script>--}}
        {{--$('#add-button').on('click', function(){--}}
            {{--window.location = '{{ route('admin.house-feature.create')  }}'--}}
        {{--});--}}

        {{--$('#sarana-table').DataTable({--}}
            {{--processing: true,--}}
            {{--serverSide: true,--}}
            {{--ajax: "{{ route('ajax.admin.house-feature') }}",--}}
            {{--columns: [--}}
                {{--{data: 'no', name: 'no'},--}}
                {{--{data: 'name', name: 'name'},--}}
                {{--{data: 'type', name: 'type'},--}}
                {{--{data: 'jumlah', name: 'jumlah'},--}}
                {{--{data: 'delete', name: 'delete'},--}}
            {{--]--}}
        {{--});--}}
        {{----}}
        {{--function deleteData(id) {--}}
            {{--$('#delete-id').val(id);--}}
            {{--$('#delete-form').submit();--}}
        {{--}--}}
    {{--</script>--}}
{{--@endsection--}}

resources/views/dashboard/admin/house-order.blade.php
@extends('dashboard.layouts.app')

@section('title', 'Listing')

@section('css')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('dashboard-assets/modules/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard-assets/modules/css/select.bootstrap4.min.css') }}">
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Pesanan</h1>
            <div class="section-header-breadcrumb">
            </div>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Data Pesanan</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped" id="order-table">
                                    <thead>
                                    <tr>
                                        <th class="text-center">
                                            #
                                        </th>
                                        <th>Pembeli</th>
                                        <th>Rumah</th>
                                        <th>Harga</th>
                                        <th>Status</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection


@section('js')
    <!-- JS Libraies -->
    <script src="{{ asset('dashboard-assets/modules/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('dashboard-assets/modules/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('dashboard-assets/modules/js/select.bootstrap4.min.js') }}"></script>

    <script>
        $('#order-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('ajax.admin.order') }}",
            createdRow: function(row, data, index){
                $(row).addClass('clickable-row');
                $(row).attr('data-href', '/admin/house-order/detail/' + data['id']);
            },
            columns: [
                {data: 'no', name: 'no'},
                {data: 'buyer', name: 'buyer'},
                {data: 'rumah', name: 'rumah'},
                {data: 'harga', name: 'harga'},
                {data: 'status_', name: 'status_'},
            ],
            drawCallback: function(){
                $('.clickable-row').on('click', function(){
                    window.location = $(this).data('href');
                });
            }
        });
    </script>
@endsection

resources/views/dashboard/admin/listing.blade.php
@extends('dashboard.layouts.app')

@section('title', 'Listing')

@section('css')
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{{ asset('dashboard-assets/modules/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard-assets/modules/css/select.bootstrap4.min.css') }}">
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>DataTables</h1>
            <div class="section-header-button">
                <a href="{{ route('admin.listing.create') }}" class="btn btn-primary">Add New</a>
            </div>
            <div class="section-header-breadcrumb">
            </div>
        </div>
        <form action="{{ route('admin.listing.update.status') }}" method="post" id="action-form">
            @csrf
            <input type="hidden" name="listing" value="-1" id="listing-update-id">
            <input type="hidden" id="status" name="status">
        </form>

        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Data Listing</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped" id="listing-table">
                                    <thead>
                                    <tr>
                                        <th class="text-center">
                                            #
                                        </th>
                                        <th>Judul</th>
                                        <th>Luas Tanah</th>
                                        <th>Luas Bangunan</th>
                                        <th>Provinsi</th>
                                        <th>Harga</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection


@section('js')
    <!-- JS Libraies -->
    <script src="{{ asset('dashboard-assets/modules/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('dashboard-assets/modules/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('dashboard-assets/modules/js/select.bootstrap4.min.js') }}"></script>

    <script>
        $('#listing-table').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{ route('ajax.admin.listing') }}",
            createdRow: function(row, data, index){
                $(row).addClass('clickable-row');
                $(row).attr('data-href', '/admin/listing/detail/' + data['id']);
            },
            columns: [
                {data: 'no', name: 'no'},
                {data: 'judul', name: 'judul'},
                {data: 'l_tanah', name: 'l_tanah'},
                {data: 'l_bangunan', name: 'l_bangunan'},
                {data: 'provinsi', name: 'provinsi'},
                {data: 'harga_format', name: 'harga_format'},
                {data: 'action', name: 'action'},
            ],
            drawCallback: function(){
                $('.clickable-row td').on('click', function(){
                    if($(this).children('button').length){
                        return;
                    }
                    window.location = $(this).parent().data('href');
                });

                $('#action-button').on('click', function(){
                    $('#status').val($(this).data('id'));
                    $('#listing-update-id').val($(this).parent().data('listing-id'));
                    $('#action-form').submit();
                });

                $('#block-button').on('click', function(){
                    $('#status').val($(this).data('id'));
                    $('#listing-update-id').val($(this).parent().data('listing-id'));
                    $('#action-form').submit();
                });
            }
        });
    </script>
@endsection